### PR TITLE
Do not disable bare RPMs which are in the pile

### PR DESCRIPTION
**Pull request by r4f4**
This avoids the following message from libsolv if there is a bare RPM
that was explicitly requested for resolution:

Problem 1 / 1:
  - conflicting requests
  - package foo-2-1.noarch is disabled

This change makes explicit-nevra test pass again.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by r4f4** [comment]
@lubomir could you check if this change doesn't break anything with real data?

**Comment by lubomir** [comment]
In my testing the resulting packages are the same with or without the patch. Good on that side. I do have one concern though: until now the order in which packages were added had no impact. Can this patch change that? Can different order of input solvables result in different results?

**Comment by r4f4** [comment]
Thank you for testing. Regarding your question, I don't think so because first we add all the input solvables to the pile and just then we do the dependency resolution, which is when this change makes a difference. I'll try to come up with a test to make sure that's the case.

**Comment by lubomir** [comment]
Aren't newly discovered dependencies added to the pile as well?

**Comment by r4f4** [comment]
Yes. And once added, a package is never removed from the pile. Since the pile is what we return as result of the dependency resolution, we can't disable the packages that are already there imho.

**Comment by r4f4** [comment]
@lubomir let me know if you think this test is not covering some case.

**Review by lubomir — APPROVED** [review]
I like the test. :+1:

**Pull request merged**
