### PR TITLE
Load filelists on demand

### PR DESCRIPTION
**Pull request by r4f4**
I can't find documentation about pool_setloadcallback. Here is what I put together looking at libsolv code and examples.
Please, let me know if I'm in the right direction. The callback doesn't seem to be called (hence the WIP).

### CODE REVIEW

**Comment by lubomir** [comment]
There is a Python example in libsolve repo, which might be useful: https://github.com/openSUSE/libsolv/blob/master/examples/pysolv#L634

**Comment by r4f4** [comment]
Alternative implementation to #21. @lubomir can you give this a try?

**Comment by lubomir** [comment]
My testing shows the output is identical to the implementation in #21. :+1:

**Comment by r4f4** [comment]
ping

**Comment by lubomir** [comment]
Is there something preventing this from being merged? As far as I can tell, it works correctly.

**Comment by igor-raits** [comment]
I Will test it myself today and merge

**Comment by igor-raits** [comment]
ugh, I thought that I've merged this!

**Comment by igor-raits** [comment]
@r4f4 that's why I pointed out in your PR ;)

**Comment by r4f4** [comment]
Ah, I just realized this. Do you want to check and merge this first and I'll rebase #40 again?

**Comment by igor-raits** [comment]
merged with few fixes in 9f9e712.

**Comment by igor-raits** [comment]
+ 8ce1358.

**Pull request closed without merging**
